### ISSUE TITLE
How do I get this to work?

### ISSUE THREAD

**Issue by Asphyixii** [zeruniverse/CryptoStego#10]
Heres my html:

```
<script src="https://cdn.jsdelivr.net/gh/zeruniverse/CryptoStego@master/src/main.js"></script>
<img src="/assets/AdeMjeFdr7IUAAAAAElFTkSuQmCC.png" id="input">
<canvas id="canvas"></canvas>
 <script>
     loadIMGtoCanvas("input", "canvas", null, 500)
     eval(readMsgFromCanvas("canvas","",0))
 </script> 
```
 
 
 Whenever I go to the page it says no img file selected

**Comment by Asphyixii** [comment]
I'm trying to just put the msg in into the image/whatever on the website, so i removed loadimgtocanvas and the canvas and had it read the msg from the image however it just says
```js
main.js:22 Uncaught ReferenceError: readMsgFromCanvas_base is not defined
    at readMsgFromCanvas (main.js:22)
    at test.html:5
    ```

**Comment by zeruniverse** [comment]
Sorry pretty busy recently. main.js only have partial code. Please use min.js inside dist. If you use main.js, you have to include all js files inside src folder. Let me know if this solves your problem
