### ISSUE TITLE
DTC issues

### ISSUE THREAD

**Issue by Krammig** [zeruniverse/CryptoStego#11]
Unfortunately the DTC option has way too much distortion. Even for just a basic 1:1 test. 

Any options/suggestions available  ? 

Also an observation. With a minimal image, for example a simple two color logo on a white background, DTC fails completely. 
It is better if the background is black, but still fails. 
It does work fully in terms of displaying stored data, however as mentioned the image distortion rate is unacceptable for use. 

Thanks

**Comment by zeruniverse** [comment]
I actually tried a lot and it’s the best distortion I can achieve. The problem is that storing machine readable information is harder than adding invisible watermark. The error tolerance is very low.
