### ISSUE TITLE
Is it possible to initiate an area that will be storing the hidden message

### ISSUE THREAD

**Issue by umarkotak** [zeruniverse/CryptoStego#6]
what i mean is
the message will be stored between 200 x 400 area
and then if i try to change anything outside that area, the message will not be affected

**Comment by zeruniverse** [comment]
It’s possible.

You can load image to a canvas, crop the image and copy target area to a
new canvas. Apply the library to the cropped area canvas and then
pixelwisely copy the result data and overwrite the corresponding area in
the original canvas. You can generate random noise outside that area.

Another option is changing the library itself, which involves a little bit
effort reading my code.

Anyway, it’s not hard. You can figure it out in less than a half day.

Thanks

**Comment by umarkotak** [comment]
i see, i think i'm gonna implement your first solution. i'm new with javascript tho

**Comment by zeruniverse** [comment]
Happy coding

**Comment by umarkotak** [comment]
thanks a lot ^^, yepp
