### ISSUE TITLE
LSB mode will crash when use PNG with transparent backgound

### ISSUE THREAD

**Issue by chenyou-fdu** [zeruniverse/CryptoStego#7]
when I try to decode some PNG with transparent backgound, my Chrome or IE will stuck and crash..

**Comment by zeruniverse** [comment]
1. Check if your bug can be reproduced in stego.js.org

2. If yes, attach your PNG and messages here. I’ll take a look when I have
time.

3. If no, take a look at the difference at the calling method. You might
did something wrong.

**Comment by chenyou-fdu** [comment]
@zeruniverse thanks for your quick reply!
I've tested on stego.js.org, using a png with transparent background a simple message "1", using Level 1 to write image
![star_png1580](https://user-images.githubusercontent.com/1531217/40152231-fc316040-59b6-11e8-82f1-3ac898d72d4f.png)
Write can be performed successfully, but the picture's background has been turned into **all black**. And this black-background png image's message **can be read successfully**.

But when I read message from a transparent background png image **with no message contained**, it will caused my Chrome **stuck and crash**.

BTW, when I try to read some message from a picture (**with background**) which has no message contained, it will show some messy characters. I don't know the algorithm behind stego, but I wonder if there any possible enhancement to make this behavior better?

Thanks!

**Comment by zeruniverse** [comment]
1. You need level 0 for LSB.

2. The algorithm was designed in the way that you can always extract
messages, but with incorrect key, the message is wrong. This is intended
such that people don’t know whether it’s something inside the image if they
don’t know the password. The crash is due to the same reason (You are
decrypting something meaningless) and again it’s intended

**Comment by zeruniverse** [comment]
To get better behaviour, you can append some verification bits everytime
you wrote message and check those bits when you extract msgs

**Comment by chenyou-fdu** [comment]
Thanks.. So the crash is intended ? I get it.. 
I indeed use level 0 for LSB.. the above comment 'level 1' is a typo. sorry.
Still the transparent backgound is turned into black when write message to a transparent png

**Comment by chenyou-fdu** [comment]
Ok, thanks for the help!
