### ISSUE TITLE
Emoji characters read back as Chinese characters

### ISSUE THREAD

**Issue by PickJBennett** [zeruniverse/CryptoStego#9]
I saved an image using your demo and encoded some emojis. When it was read back, the symbols displayed as Chinese characters. It seems like it’s a Unicode character encoding problem to me. 🤔

**Comment by zeruniverse** [comment]
Maybe 
https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder
https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder
are better options for UTF8 encoding / decoding

You may change current implementations to WebAPI and submit pull requests. I'm quite busy now with a full-time job so this feature will not come soon if you want me to implement it
